service: slack-invitation
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

  stage: dev
  region: ap-northeast-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
            - "secretsmanager:DescribeSecret"
          Resource: "*"

custom:
  environment:
    dev:
      SSM_KEY_NAME: ${file(./.env.yaml):SSM_KEY_NAME}
      SLACK_CHANNEL_NAME: ${file(./.env.yaml):SLACK_CHANNEL_NAME}
      SLACK_BOT_USER_NAME: ${file(./.env.yaml):SLACK_BOT_USER_NAME}
# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - '!./**'
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    # 環境変数を設定する
    environment:
      SSM_KEY_NAME: ${self:custom.environment.dev.SSM_KEY_NAME}
      SLACK_CHANNEL_NAME: ${self:custom.environment.dev.SLACK_CHANNEL_NAME}
      SLACK_BOT_USER_NAME: ${self:custom.environment.dev.SLACK_BOT_USER_NAME}
    events:
      - httpApi:
          path: /hello
          method: post
